#!/bin/bash
file=$1
# stage4() {
mkdir parameter;cd parameter;
echo "gf automation working..."
for i in debug_logic idor img-traversal interestingEXT interestingparams interestingsubs jsvar lfi rce redirect sqli ssrf ssti xss 
do
  echo "####################################"
  echo "$i"
  cat  $file | gf $i | tee -a  $i | wc -l
  # echo "###################################"
done;


# stage4