#!/bin/bash

# This script automates the process of using the 'gf' tool for security analysis.
# It takes a file as input and runs various 'gf' commands on it.

# Input file
file=$1

# Check if a file is provided
if [ -z "$file" ]; then
  echo "Error: Please provide a file as an argument."
  exit 1
fi

# Create a directory to store the results
mkdir parameter
cd parameter

# Print a message indicating the script is running
echo "gf automation working..."

# Loop through various 'gf' commands
for i in debug_logic idor img-traversal interestingEXT interestingparams interestingsubs jsvar lfi rce redirect sqli ssrf ssti xss; do
  # Print a separator for each command
  echo "####################################"
  echo "$i"

  # Run the 'gf' command and pipe the output to a file named after the command
  # The 'wc -l' command counts the number of lines in the output
  cat "$file" | gf "$i" | tee -a "$i" | wc -l

  # Print another separator
  # echo "###################################"
done

# Exit the script
exit 0
