#!/bin/bash

# Install dependencies
# apt-get update
folder() {
mkdir python 
python -m venv python  
apt-get install -y python3-pip git curl jq
/bin/pip3 install subfinder assetfinder chaos alterx amass subjack shodan masscan nmap dirsearch
cd python
}
# Get the target domain from command line arguments
domain="$1"

output () {
# Create output directories
mkdir -p recon_results/"$domain"/subdomains
mkdir -p recon_results/"$domain"/takeover
mkdir -p recon_results/"$domain"/internal_ips
mkdir -p recon_results/"$domain"/port_scans
mkdir -p recon_results/"$domain"/directory_bruteforce
}

subdomain () {
# Subdomain enumeration
echo "[*] Enumerating subdomains for $domain"
subfinder -d "$domain"  -o recon_results/"$domain"/subdomains/sub1.txt
assetfinder --subs-only "domains" | tee -a recon_results/"$domain"/subdomains/sub2.txt  
#chaos -d "$domain" -o recon_results/"$domain"/subdomains/sub3.txt
#echo "$domain" | alterx -o recon_results/"$domain"/subdomains/sub4.txt 
#amass enum -norecursive -noalts -d "$domain" -o recon_results/"$domain"/subdomains/sub5.txt
# findomain --external-subdomains --output --target "$domain" --unique-output | 
cat recon_results/"$domain"/subdomains/*.txt | sort -u > recon_results/"$domain"/subdomains/all_subdomains.txt
}

takeover() {
# Subdomain takeover check
echo "[*] Checking for subdomain takeovers"
subjack -w recon_results/"$domain"/subdomains/all_subdomains.txt -t 100 -timeout 30 -ssl -c /usr/share/subjack/fingerprints.json -v > recon_results/"$domain"/takeover/takeover.txt
}

sho () { 
# Find internal IPs using Shodan
echo "[*] Finding internal IPs for $domain using Shodan"
shodan search "hostname:$domain" --fields ip_str,port,org > recon_results/"$domain"/internal_ips/internal_ips.txt
}
por() {

# Port scanning
echo "[*] Performing port scanning on $domain"
nmap "$domain" -p1-65535 --rate=1000 | tee -a  recon_results/"$domain"/port_scans/port.txt
}

dir () {
# Directory brute-forcing
echo "[*] Performing directory brute-forcing on $domain"
dirsearch -u "$domain" -e * -o recon_results/"$domain"/directory_bruteforce/dirsearch.txt
}

#folder
output
subdomain
takeover
sho
por
dir
