#!/bin/bash

echo "@fancybearin"

# Creating the folder 
stage0() {
    cd && pwd;
    mkdir bugbounty;cd bugbounty;
    pwd;
    mkdir "$domain.";cd "$domain." && pwd;
    clear
}

#subdomain enumeration 
subdomain () {
    subfinder -d $domain | tee -a  subdomain &&
    assetfinder -subs-only $domain | tee -a subdomain &&
    amass enum -norecursive -noalts -d $domain | tee -a subdomain &&    
    chaos -d $domain | tee -a subdomain &&
    alterx -d $domain | tee -a subdomain &&
    findomain --external-subdomains --output --target "$domain" --unique-output subdomain;
    cat subdomain | sort -u | tee -a domain.txt

    # testing for subdamin takeover
    subjack -w totalsub4 -t 100 -timeout 30 -ssl -c /home/bear/go/pkg/mod/github.com/haccer/subjack@v0.0.0-20201112041112-49c51e57deab/fingerprints.json -v 3 >> takeover"
}

link () {
    cat domain.txt | httpx | tee -a link.txt" &  cat domain.txt | httprobe | tee -a link.txt;
    wait
    cat link.txt | sort -u | tee -a link2.txt
    cat link2.txt | gau | tee -a extract.txt & cat linksort.txt | waybackurls | tee -a extract.txt;
    wait
    cat extract.txt | sort -u | tee -a oldext.txt;
    cat oldext.txt | httpx | tee -a old.txt &
    cat oldext.txt | httprobe -c 10 | tee -a old.txt&
    cat oldext.txt | katana -d 4 -o old.txt &
    cat oldext.txt | galer -o old.txt;
    wait
    cat old.txt | sort -u | tee -a urls.txt ;
    gf_auto urls.txt
}

testing () {
    xss () {
      cat xss | Gxss | tee -a  gxss"
      cat gxss| dalfox pipe | tee -a Dalfox"
    }
    
    ssrf () {
       ssrftool -domains link2.txt -payloads /home/bear/.git/ssrf-tool/important/payloads.txt -silent=false -paths=true -patterns ~/ssrf-tool/important/patterns.txt | tee -a ssrf1 ;
       ssrftool -domains oldext.txt -payloads /home/bear/.git/ssrf-tool/important/payloads.txt -silent=false -paths=true -patterns ~/ssrf-tool/important/patterns.txt | tee -a ssrf2 ;
       ssrftool -domains ssrf -payloads /home/bear/.git/ssrf-tool/important/payloads.txt -silent=false -paths=true -patterns ~/ssrf-tool/important/patterns.txt | tee -a ssrf3 ;
     }

    xss
    ssrf
}

#logic area
configure () {
 select option in extraction testing neutral exit 
 do
    case $option in 
        extraction)
        clear
                echo "extraction." 
                echo "for back press 5 and double enter it."
                stage0
                select process in subdomain link same testing back 
                do
                    case $process in 
                        subdomain)
                               subdomain
                               continue
                               ;;
                        link)
                            link
                           continue
                           ;;
                        same)
                           echo "both are running"
                           subdomain
                           link
                           continue
                           ;;    
                        testing)
                             echo "testing is start."
                            testing
                              break
                            ;;
                         back)
                            break 
                            ;; 
                           *)
                            echo "try again.."
                            continue
                        ;;
                    esac
                done
                continue
                ;;
        
        testing)
        clear
                echo "testing is start."
                testing
                break
                ;;
        neutral)
        clear 
            echo "no option to select"
            subdomain
            clear
            link
            clear
            testing
           break
           ;;

        exit)
            break 
           ;; 
            *)
            echo "try again.."
            continue
             ;;
        esac
 done
}

domain=$1
configure
